# Travis-CI
dist: bionic
language: python
os: linux

matrix:
  include:
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    # Docker dev image
    - sudo: true
      services:
        - docker

      before_install:
        - pip3 install -r requirements.txt
      install: []

      script:
        - docker build --tag "$IMAGE_NAME" .
