# Travis-CI
dist: bionic
language: shell
os: linux

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - sudo apt-get update
  - sudo apt-ge install docker-ce -y


before_script:
  - docker version
  - docker buildx create --name moc_builder --use
  - |
      if [ -n "$TRAVIS_TAG" ]; then
        export SPECIFIC_TAG="-t '$IMAGE_TAG:$TRAVIS_TAG'"
      fi

script: docker buildx build --platform "$TARGET_ARCH" --progress plain -t $IMAGE_TAG $SPECIFIC_TAG
