version: '3.7'

services:
  server:
    image: caddy:alpine
    restart: always
    environment: 
      - APP_URL=${APP_URL}
    volumes:
      # Vhost configuration
      - ./config/Caddyfile:/etc/caddy/Caddyfile

      # Configure your mounted directories, make sure the folder 'public' and 'storage'
      # exist, before mounting them
     # -  public:/var/www/app/public
     # -  storage:/var/www/app/storage
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - ${APP_URL}
